# Generated by Django 3.1.1 on 2020-09-27 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('prod_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('link', models.URLField()),
                ('gender', models.CharField(max_length=10)),
                ('category', models.CharField(max_length=10)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity', models.FloatField()),
                ('sim_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_prod', to='recommendapp.product')),
                ('target_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_prod', to='recommendapp.product')),
            ],
        ),
    ]
